### ISSUE TITLE
TreeEvents function is called twice

### ISSUE THREAD

**Issue by bouffekai** [vinz3872/vuejs-tree#41]
Hello,

I'm trying to call `myCheckedFunction` (TreeEvents function) but it calls twice (even in your codesandbox, when we check an item, 2 console.log() are triggered.
How can I fix this ?

Thank you for your help
Jeremy

**Comment by bouffekai** [comment]
@vinz3872 ?

**Comment by vinz3872** [comment]
:wave: Hello,
Yes, indeed the the event is sent twice, i've fixed it in the commit https://github.com/vinz3872/vuejs-tree/commit/5d962a53f94e2c74f91171e96b1dae01444d578d
i'll create a new package version soon

**Comment by piliadis** [comment]
Hi @vinz3872 and thanks for your component! Just wanted to verify that this issue has been resolved. I have still the same behavior although I'm in version 3.0.2 and just also checked the codesandbox (fig)

![Screenshot 2022-07-07 125355](https://user-images.githubusercontent.com/28279034/177746254-68954cb5-10f1-4cb8-894f-0fc22943460d.png)

Thanks in advance,
Petros
